config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#index'
  resources 'users', only: [:index]
  resources 'books', only: [:index, :new, :create] do
    member do
      post  'add_shelf'
    end
  end
  namespace 'api' do
    resources 'books', only: [:index], defaults: {format: 'json'}
  end
end

app/views/module/_menu.html.haml
.menu
  = link_to root_path do
    .menu__title
      .menu__title__left
        Personal
      = fa_icon 'leaf'
      .menu__title__right
        Library
  .menu__user
    - @user_name = 'やあ、一見さん'
    - @url = new_user_session_path
    - @action = "get"
    - @caption = 'Log in'
    - @fa_icon_sign = 'sign-in'
    - if user_signed_in?
      - @user_name = "よく来たな、#{current_user.name}"
      - @url = destroy_user_session_path 
      - @action = "delete"
      - @caption = 'Log out'
      - @fa_icon_sign = 'sign-out'
    .menu__user__name
      = @user_name
    .menu__user__sign-in
      = link_to @url, method: @action do
        = fa_icon "#{@fa_icon_sign}", class: 'menu__user__sign-in__icon'
        = @caption
    - if user_signed_in?
      .menu__user__book-shelf
        -# ログインユーザのbook一覧表示
        = link_to users_path do
          = fa_icon 'book'
          My書架
    - else
      .menu__user__sign-up
        = link_to new_user_registration_path do
          = fa_icon 'user-plus'
          ユーザ登録

  -# DBから検索
  .menu__search-form
    = form_tag do
      %fieldset.menu__search-form__group
        %legend.menu__search-form__group__caption
          = fa_icon 'search'
          書架から検索
        .menu__search-form__field
          .menu__search-form__field__caption
            = label_tag :title, '書籍名'
          .menu__search-form__field__input
            = text_field_tag :book_title_shelf, '', class: 'menu__search-form__field__input__shelf'
        .menu__search-form__field
          .menu__search-form__field__caption
            = label_tag :author, '著者名'
          .menu__search-form__field__input
            = text_field_tag :book_author_shelf, '', class: 'menu__search-form__field__input__shelf'
        .menu__search-form__field
          .menu__search-form__field__caption
            = label_tag :isbn, 'ISBN'
          .menu__search-form__field__input
            = number_field_tag :book_isbn_shelf, '', class: 'menu__search-form__field__input__shelf', placeholder: "13桁の数字を入力", maxlength: 13
  - if user_signed_in?
    -# 外部サイト（楽天）から検索
    .menu__search-form
      = form_with(url: new_book_path, method: 'GET', local: true) do |f|
        %fieldset.menu__search-form__group
          %legend.menu__search-form__group__caption
            = fa_icon 'search'
            楽天から検索
          .menu__search-form__field
            .menu__search-form__field__caption
              = f.label :title, '書籍名'
            .menu__search-form__field__input
              = f.text_field :title, class: 'menu__search-form__field__input__title'
          .menu__search-form__field
            .menu__search-form__field__caption
              = f.label :author, '著者名'
            .menu__search-form__field__input
              = f.text_field :author, class: 'menu__search-form__field__input__author'
          .menu__search-form__field
            .menu__search-form__field__caption
              = f.label :isbn, 'ISBN'
            .menu__search-form__field__input
              = f.number_field :isbn, class: 'menu__search-form__field__input__isbn', placeholder: "13桁の数字を入力", maxlength: 13
          = f.submit '検索', class: 'menu__search-form__find-btn', id: 'external-find-btn'
    .menu__credit
      <!-- Rakuten Web Services Attribution Snippet FROM HERE -->
      <a href="https://webservice.rakuten.co.jp/" target="_blank">Supported by Rakuten Developers</a>
      <!-- Rakuten Web Services Attribution Snippet TO HERE -->